name: 'build images'

on: workflow_dispatch

jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        run: ./download_signal-cli.sh

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: armv7-unknown-linux-gnueabihf

      - name: Checkout zkgroup
        uses: actions/checkout@master
        with:
          repository: signalapp/zkgroup
        continue-on-error: true

      - name: Build zkgroup
        run: |
          cd ffi/java
          make

      - name: Checkout libsignal-client
        uses: actions/checkout@master
        with:
          repository: signalapp/libsignal-client

      - name: Build libsignal-client
        run: |
          cd java
          ./build_jni.sh desktop

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=${{secrets.DOCKER_USERNAME}}/${GITHUB_REPOSITORY#*/}
          VERSION=${{ env.tag_name }}
          SHORTREF=${GITHUB_SHA::8}

          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${SHORTREF},${DOCKER_IMAGE}:latest"

          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: ${{ steps.prep.outputs.tags}}
          build-args:
            SIGNAL_ASSET=${{ env.asset }}